### ISSUE TITLE
The problem farbic Mixin by fabric 20w15a,The runtime code failed to start.

### ISSUE THREAD

**Issue by stepheninchina** [FabricMC/Mixin#29]
I found an incompatibility between fabric load and Mixins, and I removed the code to enable fabric mods,error logs list:
`Exception in thread "main" org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [modid.mixins.json:ElementMixin] from phase [DEFAULT] in config [modid.mixins.json] FAILED during PREPARE
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:591)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:518)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:440)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:416)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:190)
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
        at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'io.github.baka4n.mixin.ElementMixin' was not found
        at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:855)
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:715)
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:652)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:515)
        ... 13 more
Caused by: java.lang.ClassNotFoundException: The specified mixin 'io.github.baka4n.mixin.ElementMixin' was not found
        at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1297)
        at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:848)
        ... 16 more`
Reference Code:
`
package io.github.elementera.mixin;

import net.minecraft.client.gui.screen.TitleScreen;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

@Mixin(TitleScreen.class)
public class ElementMixin {
	@Inject(at = @At("HEAD"), method = "init()V")
	private void init(CallbackInfo info) {
		System.out.println("This line is printed by an example mod mixin!");
	}
}

`

**Comment by modmuss50** [comment]
The package name in the mixin json does not match the package name of the class you posted

**Comment by stepheninchina** [comment]
{
  "required": true,
  "minVersion": "0.8",
  "package": "io.github.baka4n.mixin",
  "compatibilityLevel": "JAVA_8",
  "mixins": [
  ],
  "client": [
    "ElementMixin"
  ],
  "injectors": {
    "defaultRequire": 1
  }
}

**Comment by stepheninchina** [comment]
This is when I suddenly remembered my module development plan today and retested it to confirm the problem.

**Comment by stepheninchina** [comment]
My configuration still works at 20w14a build2,But not to the nerwer version

**Comment by stepheninchina** [comment]
sorry, i forget something
