### ISSUE TITLE
Manifold Extensions + Mixins Cause Crashes

### ISSUE THREAD

**Issue by gudenau** [FabricMC/Mixin#42]
When trying to use [Manifold's extensions](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-ext) anywhere in the project mixin dies because of a "non-public method".

```
[16:28:37] [main/ERROR] (mixin) modid.mixins.json:MinecraftClientAccessor: Interface mixin contains a non-public method! Found null in modid.mixins.json:MinecraftClientAccessor
 org.spongepowered.asm.mixin.transformer.throwables.InvalidInterfaceMixinException: Interface mixin contains a non-public method! Found null in modid.mixins.json:MinecraftClientAccessor
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorInterface.prepareMethod(MixinPreProcessorInterface.java:61) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.prepare(MixinPreProcessorStandard.java:181) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$State.validate(MixinInfo.java:321) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validate(MixinInfo.java:904) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:674) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:542) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.10.6+build.214@net.fabricmc.yarn.1_16_4.1.16.4+build.6-v2.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.10.6+build.214@net.fabricmc.yarn.1_16_4.1.16.4+build.6-v2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-loader-0.10.6+build.214@net.fabricmc.yarn.1_16_4.1.16.4+build.6-v2.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) [?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:222) [fabric-loader-0.10.6+build.214@net.fabricmc.yarn.1_16_4.1.16.4+build.6-v2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.6+build.214@net.fabricmc.yarn.1_16_4.1.16.4+build.6-v2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.6+build.214@net.fabricmc.yarn.1_16_4.1.16.4+build.6-v2.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
```

Expected behavior:
I should be able to add an extension and have mixins not throw, enabling me to "add" methods to existing classes.

Steps to reproduce:

1. [Clone this minimal example](https://github.com/gudenau/minecraft-extension-crash)
2. Try to run Minecraft
3. Crashes

**Comment by Chocohead** [comment]
You haven't clarified that Manifold isn't actually putting non-public methods in an interface

**Comment by modmuss50** [comment]
I dont believe this is a mixin issue, and not something mixin can fix. I would look at what its doing to the bytecode before you start blaming mixin on this.

**Comment by modmuss50** [comment]
If it is indeed a mixin issue please open an issue to upstream mixin as well.

**Comment by gudenau** [comment]
This is interesting. It's adding a static constructor to the interface.

```
// class version 52.0 (52)
// access flags 0x601
public abstract interface net/fabricmc/example/mixin/MinecraftClientAccessor {

  // compiled from: MinecraftClientAccessor.java

  @Lorg/spongepowered/asm/mixin/Mixin;(value={net.minecraft.client.MinecraftClient.class}) // invisible

  // access flags 0x9
  public static getLOGGER()Lorg/apache/logging/log4j/Logger;
  @Lorg/spongepowered/asm/mixin/gen/Accessor;()
   L0
    LINENUMBER 12 L0
    NEW java/lang/Object
    DUP
    INVOKESPECIAL java/lang/Object.<init> ()V
    CHECKCAST org/apache/logging/log4j/Logger
    ARETURN
    MAXSTACK = 2
    MAXLOCALS = 0

  // access flags 0x401
  public abstract getWindowProvider()Lnet/minecraft/client/util/WindowProvider;
  @Lorg/spongepowered/asm/mixin/gen/Accessor;()

  // access flags 0x8
  static <clinit>()V
   L0
    LINENUMBER 12 L0
    INVOKESTATIC manifold/rt/api/IBootstrap.dasBoot ()Z (itf)
    POP
    RETURN
    MAXSTACK = 1
    MAXLOCALS = 0
}
```

**Comment by gudenau** [comment]
Closed as I solved this with a clever build script and seems to be a fault with Manifold itself.
